name: twinned_mobile
description: "Boodskap Digital Twin Client Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  curved_navigation_bar: ^1.0.3
  expandable_datatable: ^0.0.7
  flutter:
    sdk: flutter

  nocode_commons:
    git:
      url: https://github.com/boodskap/nocode_commons.git

  twinned_widgets:
    git:
      url: https://github.com/boodskap/twinned_widgets.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/Platform-digitaltwin.png" 

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/settings.txt
    - assets/images/